default_language_version:
  python: python3

fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-byte-order-marker
  - id: check-ast
  - id: check-case-conflict
  - id: check-executables-have-shebangs
    exclude: ^static/
  - id: check-merge-conflict
  - id: debug-statements
  - id: name-tests-test
    args: [ "--django" ]
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: Makefile

- repo: https://github.com/pycqa/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      args: ['-iii', '-ll', '--skip=B308,B703']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    args: ["toml"]

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
  - id: flake8
    language_version: python3
    additional_dependencies: [
      "flake8-bugbear",
      "flake8-comprehensions",
      "flake8-mutable",
      "flake8-print",
      "flake8-simplify",
    ]

- repo: local
  hooks:
  - id: migrations-check
    language: system
    name: Check for uncreated migrations.
    entry: bash -c "./app/manage.py makemigrations --check --dry-run"
    types: ["python"]
    pass_filenames: false
