# Generated by Django 4.2.4 on 2023-08-15 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_celery_beat", "0018_improve_crontab_helptext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
            },
        ),
        migrations.CreateModel(
            name="StockUserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "checking_time_interval",
                    models.IntegerField(
                        choices=[
                            (1, "1 minuto"),
                            (5, "5 minutos"),
                            (10, "10 minutos"),
                            (30, "30 minutos"),
                            (60, "60 minutos"),
                            (90, "90 minutos"),
                            (120, "120 minutos"),
                        ],
                        default=10,
                    ),
                ),
                ("buy_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("sell_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("stock", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stocks.stock")),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transaction_type", models.CharField(choices=[("BUY", "Comprar"), ("SELL", "Vender")], max_length=4)),
                ("amount", models.PositiveIntegerField()),
                ("price_per_stock", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "stock_user_profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stocks.stockuserprofile"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stockuserprofile",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stocks.userprofile"),
        ),
        migrations.CreateModel(
            name="PriceLogUserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField()),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("open", models.DecimalField(decimal_places=2, max_digits=10)),
                ("close", models.DecimalField(decimal_places=2, max_digits=10)),
                ("high", models.DecimalField(decimal_places=2, max_digits=10)),
                ("low", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.IntegerField()),
                (
                    "stock_user_profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stocks.stockuserprofile"),
                ),
            ],
            options={
                "verbose_name": "Price Log",
                "verbose_name_plural": "Prices Logs",
            },
        ),
        migrations.AlterUniqueTogether(
            name="stockuserprofile",
            unique_together={("user", "stock")},
        ),
    ]
