# Generated by Django 4.2.4 on 2023-08-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("checking_time_in_minutes", models.IntegerField(default=5)),
            ],
        ),
    ]
