# Generated by Django 4.2.4 on 2023-08-17 01:17
from django.contrib.auth import get_user_model
from django.db import migrations


def create_test_superuser(apps, schema_editor):
    user = get_user_model()
    admin = user.objects.create_superuser(username="test_user", password="12345678")
    admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_auto_20230815_1201"),
    ]

    operations = [migrations.RunPython(create_test_superuser)]
